<a href="https://colab.research.google.com/github/BabeChibi/Python_colab/blob/main/Preprocessing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

//21 maret 2021
//A11_2018_10844

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


numpy use comp matriks. matplotlib use grafic

In [40]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

pd.read_csv call data session. iloc call record values. + get first record - get last record

In [41]:
print(x)

[['France' 44.0 72000.0 2000.0]
 ['Spain' 27.0 48000.0 3000.0]
 ['Germany' 30.0 54000.0 4000.0]
 ['Spain' 38.0 61000.0 nan]
 ['Germany' 40.0 nan 10000.0]
 ['France' 35.0 58000.0 20000.0]
 ['Spain' nan 52000.0 3000.0]
 ['France' 48.0 79000.0 5000.0]
 ['Germany' 50.0 83000.0 60000.0]
 ['France' 37.0 67000.0 80000.0]]


In [42]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [43]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:,1:4])
x[:,1:4] = imputer.transform(x[:,1:4])

In [44]:
print(x)

[['France' 44.0 72000.0 2000.0]
 ['Spain' 27.0 48000.0 3000.0]
 ['Germany' 30.0 54000.0 4000.0]
 ['Spain' 38.0 61000.0 20777.777777777777]
 ['Germany' 40.0 63777.77777777778 10000.0]
 ['France' 35.0 58000.0 20000.0]
 ['Spain' 38.77777777777778 52000.0 3000.0]
 ['France' 48.0 79000.0 5000.0]
 ['Germany' 50.0 83000.0 60000.0]
 ['France' 37.0 67000.0 80000.0]]


In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [46]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0 2000.0]
 [0.0 0.0 1.0 27.0 48000.0 3000.0]
 [0.0 1.0 0.0 30.0 54000.0 4000.0]
 [0.0 0.0 1.0 38.0 61000.0 20777.777777777777]
 [0.0 1.0 0.0 40.0 63777.77777777778 10000.0]
 [1.0 0.0 0.0 35.0 58000.0 20000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0 3000.0]
 [1.0 0.0 0.0 48.0 79000.0 5000.0]
 [0.0 1.0 0.0 50.0 83000.0 60000.0]
 [1.0 0.0 0.0 37.0 67000.0 80000.0]]


In [47]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [48]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 1)

In [50]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0 3000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778 10000.0]
 [1.0 0.0 0.0 44.0 72000.0 2000.0]
 [0.0 0.0 1.0 38.0 61000.0 20777.777777777777]
 [0.0 0.0 1.0 27.0 48000.0 3000.0]
 [1.0 0.0 0.0 48.0 79000.0 5000.0]
 [0.0 1.0 0.0 50.0 83000.0 60000.0]
 [1.0 0.0 0.0 35.0 58000.0 20000.0]]


In [51]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0 4000.0]
 [1.0 0.0 0.0 37.0 67000.0 80000.0]]


In [52]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,4:] = sc.fit_transform(x_train[:,4:])
x_test[:,4:] = sc.transform(x_test[:,4:])

In [53]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 -1.0781259408412425 -0.6835250436076243]
 [0.0 1.0 0.0 40.0 -0.07013167641635372 -0.29989851579220933]
 [1.0 0.0 0.0 44.0 0.633562432710455 -0.7383288332955408]
 [0.0 0.0 1.0 38.0 -0.30786617274297867 0.2907645508442232]
 [0.0 0.0 1.0 27.0 -1.420463615551582 -0.6835250436076243]
 [1.0 0.0 0.0 48.0 1.232653363453549 -0.5739174642317915]
 [0.0 1.0 0.0 50.0 1.5749910381638885 2.440290968603612]
 [1.0 0.0 0.0 35.0 -0.5646194287757332 0.2481393810869549]]


In [54]:
print(x_test)

[[0.0 1.0 0.0 30.0 -0.9069571034860727 -0.6287212539197079]
 [1.0 0.0 0.0 37.0 0.2056403393225306 3.536366762361941]]
